#https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
server:
  port: ${TRADETARIFF_PORT}
management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: health, info
      base-path: /admin
      path-mapping: 
        health: health-check
info:
    app:
        name: tradetariff microservice
        version: 0.1-SNAPSHOT
spring:
  security:
      user:
        name: ${TRADETARIFF_BASIC_AUTH_LOGIN}
        password: ${TRADETARIFF_BASIC_AUTH_PASSWORD}
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false

spring.jpa:
    hibernate.ddl-auto: create-drop

spring.datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL
