export DATABASE_DB_USER=SA
export DATABASE_DB_PASSWORD=dockerPassword1!
export DATABASE_DB_PORT=1401
export DATABASE_DB_NAME=trade_tariff
export DATABASE_DB_HOST=localhost
export DATABASE_DB_CONNECTION_STRING="jdbc:h2:mem:testdb"

export DB_USER=$DATABASE_DB_USER
export DB_PASSWORD=$DATABASE_DB_PASSWORD
export DB_PORT=$DATABASE_DB_PORT
export DB_NAME=$DATABASE_DB_NAME
export DB_HOST=$DATABASE_DB_HOST
export BASE_SERVICE_DB_PASSWORD=${SERVICE_DB_PASSWORD}

export TRUST_SERVER_CERTIFICATE=true

export SERVICE_USER=importer
export SERVICE_PASSWORD=password123
